### ISSUE TITLE
 Unable to run “facial_recognition.py ”

### ISSUE THREAD

**Issue by bingws** [richmondu/libfaceid#13]
I found errors in 348 lines, 383 lines ，384 lines and 454 lines. But I can not change? The live detection function is not available.
@richmondu

**Comment by dahlan77** [comment]
ImportError: cannot import name 'FaceLivenessDetectorModels'

I got same issue

**Comment by richmondu** [comment]
Install requirements.txt to get the correct versions of libraries.
Refer to testing_webcam_livenessdetection.py for sample usage of liveness decttion.

**Comment by dahlan77** [comment]
can we detect multiple person with different name?

**Comment by richmondu** [comment]
Yes, detection and recognition is done face by face.

In the examples, i just detect and recognize one face.
To recognize many faces, just do recognition on all detected faces.

**Comment by dahlan77** [comment]
i created another face but still only can detect one face..

what we do if we want to detect our trained multiple faces

**Comment by richmondu** [comment]
Please read the README file. Answers to basic questions can be found there.
