### ISSUE TITLE
Unknown face

### ISSUE THREAD

**Issue by KumailHussain** [richmondu/libfaceid#19]
I am using mtcnn as detector, encoder as facenet, classifier linear SVM and also tried neural network
training dataset 100 images each class.
When an unknown face is standing in front of camera it's classifying it from the known people and with  confidence score more than 90%  . What is wrong with the implementation

**Comment by richmondu** [comment]
These stuffs need to be tuned based on the dataset.
There is no one-size fits all face recognition.
Otherwise, Amazon, Google or Microsoft would have release it already.

Tune the parameters. I have provided the code. Go deeper.
