### ISSUE TITLE
classifier 

### ISSUE THREAD

**Issue by riyaj8888** [richmondu/libfaceid#2]
if i want to use deep cnn as clasifier how do use it?  can u help me in it

**Comment by richmondu** [comment]
are you serious? :(

1. Add your dataset 
   ex. datasets/riyaj/1.jpg, datasets/not_riyaj/1.jpg
2. Train your model using your dataset
   Update facial_recognition_training.bat to specify your chosen model
   Run facial_recognition_training.bat
3. Test your model with a webcam
   Update facial_recognition_testing_webcam.bat to specify your chosen model
   Run facial_recognition_testing_webcam.bat

**Comment by riyaj8888** [comment]
Do u know why results of confidence score and class name are continuously
fluctuating ? What will be the problem? Is it with embedding or classifier?
Please can u guide me?
