### ISSUE TITLE
ImportError: cannot import name 'FaceLivenessDetectorModels'

### ISSUE THREAD

**Issue by imaddyx** [richmondu/libfaceid#20]
Whenever I try to run facial_recognition.py script it gives an error ImportError: cannot import name 'FaceLivenessDetectorModels'
on this line 348 : from libfaceid.liveness import FaceLivenessDetectorModels, FaceLiveness 
I checked the liveness.py file and there was no class defined as  "FaceLivenessDetectorModels" but I found another class named ''FaceLivenessModels''. Can anyone suggest me the proper solution?
Regards

**Comment by richmondu** [comment]
Issue fixed. File updated to use FaceLivenessModels.
