### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by edurdag** [richmondu/libfaceid#3]
thanks for sharing and i have cmake error which version used ?
i have win7
thanks for interesting

Collecting tensorboard<1.9.0,>=1.8.0 (from tensorflow==1.8.0->-r requirements.tx
t (line 9))
  Using cached https://files.pythonhosted.org/packages/59/a6/0ae6092b7542cfedba6
b2a1c9b8dceaf278238c39484f3ba03b03f07803c/tensorboard-1.8.0-py3-none-any.whl
Collecting gast>=0.2.0 (from tensorflow==1.8.0->-r requirements.txt (line 9))
Requirement already satisfied: wheel>=0.26 in c:\users\eud\appdata\local\program
s\python\python36\lib\site-packages (from tensorflow==1.8.0->-r requirements.txt
 (line 9)) (0.32.3)
Collecting protobuf>=3.4.0 (from tensorflow==1.8.0->-r requirements.txt (line 9)
)
  Using cached https://files.pythonhosted.org/packages/e8/df/d606d07cff0fc8d22ab
cc54006c0247002d11a7f2d218eb008d48e76851d/protobuf-3.6.1-cp36-cp36m-win_amd64.wh
l
Collecting pyyaml (from keras==2.0.8->-r requirements.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/4f/ca/5fad249c5032270540c
24d2189b0ddf1396aac49b0bdc548162edcf14131/PyYAML-3.13-cp36-cp36m-win_amd64.whl
Collecting psutil (from facenet==1.0.3->-r requirements.txt (line 12))
  Using cached https://files.pythonhosted.org/packages/3b/15/62d1eeb4c015e20295e
0197f7de0202bd9e5bcb5529b9503932decde2505/psutil-5.4.8-cp36-cp36m-win_amd64.whl
Collecting requests (from facenet==1.0.3->-r requirements.txt (line 12))
  Using cached https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353
c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl
Collecting matplotlib (from facenet==1.0.3->-r requirements.txt (line 12))
  Using cached https://files.pythonhosted.org/packages/b1/56/569c83515c10146fd0a
a09e086816b12e301d0811048e3354a6e9b77ba9a/matplotlib-3.0.2-cp36-cp36m-win_amd64.
whl
Collecting Pillow (from facenet==1.0.3->-r requirements.txt (line 12))
  Using cached https://files.pythonhosted.org/packages/bd/39/c76eaf781343162bdb1
cf4854cb3bd5947a87ee44363e5acd6c48d69c4a1/Pillow-5.3.0-cp36-cp36m-win_amd64.whl
Collecting Werkzeug>=0.14 (from flask==1.0.2->-r requirements.txt (line 13))
  Using cached https://files.pythonhosted.org/packages/20/c4/12e3e56473e52375aa2
9c4764e70d1b8f3efa6682bef8d0aae04fe335243/Werkzeug-0.14.1-py2.py3-none-any.whl
Collecting Jinja2>=2.10 (from flask==1.0.2->-r requirements.txt (line 13))
  Using cached https://files.pythonhosted.org/packages/7f/ff/ae64bacdfc95f27a016
a7bed8e8686763ba4d277a78ca76f32659220a731/Jinja2-2.10-py2.py3-none-any.whl
Collecting click>=5.1 (from flask==1.0.2->-r requirements.txt (line 13))
  Using cached https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257
104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl
Collecting itsdangerous>=0.24 (from flask==1.0.2->-r requirements.txt (line 13))

  Using cached https://files.pythonhosted.org/packages/76/ae/44b03b253d6fade317f
32c24d100b3b35c2239807046a4c953c7b89fa49e/itsdangerous-1.1.0-py2.py3-none-any.wh
l
Collecting html5lib==0.9999999 (from tensorboard<1.9.0,>=1.8.0->tensorflow==1.8.
0->-r requirements.txt (line 9))
Collecting markdown>=2.6.8 (from tensorboard<1.9.0,>=1.8.0->tensorflow==1.8.0->-
r requirements.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/7a/6b/5600647404ba15545ec
37d2f7f58844d690baf2f81f3a60b862e48f29287/Markdown-3.0.1-py2.py3-none-any.whl
Collecting bleach==1.5.0 (from tensorboard<1.9.0,>=1.8.0->tensorflow==1.8.0->-r
requirements.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/33/70/86c5fec937ea4964184
d4d6c4f0b9551564f821e1c3575907639036d9b90/bleach-1.5.0-py2.py3-none-any.whl
Requirement already satisfied: setuptools in c:\users\eud\appdata\local\programs
\python\python36\lib\site-packages (from protobuf>=3.4.0->tensorflow==1.8.0->-r
requirements.txt (line 9)) (39.0.1)
Collecting urllib3<1.25,>=1.21.1 (from requests->facenet==1.0.3->-r requirements
.txt (line 12))
  Using cached https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090
d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests->facenet==1.0.3->-r requirements
.txt (line 12))
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b64
87b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting idna<2.9,>=2.5 (from requests->facenet==1.0.3->-r requirements.txt (l
ine 12))
  Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1
cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests->facenet==1.0.3->-r requirements.tx
t (line 12))
  Using cached https://files.pythonhosted.org/packages/9f/e0/accfc1b56b57e9750eb
a272e24c4dddeac86852c2bebd1236674d7887e8a/certifi-2018.11.29-py2.py3-none-any.wh
l
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 (from matplotlib->facenet==1
.0.3->-r requirements.txt (line 12))
  Using cached https://files.pythonhosted.org/packages/71/e8/6777f6624681c8b9701
a8a0a5654f3eb56919a01a78e12bf3c73f5a3c714/pyparsing-2.3.0-py2.py3-none-any.whl
Collecting kiwisolver>=1.0.1 (from matplotlib->facenet==1.0.3->-r requirements.t
xt (line 12))
  Using cached https://files.pythonhosted.org/packages/44/72/16630c3392eba03788a
d87949390516bbc488e8e118047a3b824631d21a6/kiwisolver-1.0.1-cp36-none-win_amd64.w
hl
Collecting cycler>=0.10 (from matplotlib->facenet==1.0.3->-r requirements.txt (l
ine 12))
  Using cached https://files.pythonhosted.org/packages/f7/d2/e07d3ebb2bd7af69644
0ce7e754c59dd546ffe1bbe732c8ab68b9c834e61/cycler-0.10.0-py2.py3-none-any.whl
Collecting python-dateutil>=2.1 (from matplotlib->facenet==1.0.3->-r requirement
s.txt (line 12))
  Using cached https://files.pythonhosted.org/packages/74/68/d87d9b36af36f44254a
8d512cbfc48369103a3b9e474be9bdfe536abfc45/python_dateutil-2.7.5-py2.py3-none-any
.whl
Collecting MarkupSafe>=0.23 (from Jinja2>=2.10->flask==1.0.2->-r requirements.tx
t (line 13))
  Using cached https://files.pythonhosted.org/packages/9d/80/9a5daf3ed7b8482e72e
e138cef602b538cfba5c507e24e39fb95c189b16b/MarkupSafe-1.1.0-cp36-cp36m-win_amd64.
whl
Building wheels for collected packages: dlib
  Running setup.py bdist_wheel for dlib ... error
  Complete output from command c:\users\eud\appdata\local\programs\python\python
36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\eud\\AppDa
ta\\Local\\Temp\\pip-install-f6j37fi9\\dlib\\setup.py';f=getattr(tokenize, 'open
', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(co
de, __file__, 'exec'))" bdist_wheel -d C:\Users\eud\AppData\Local\Temp\pip-wheel
-4kr5gr6p --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  package init file 'dlib\__init__.py' not found (or not a regular file)
  running build_ext
  Building extension for Python 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 03:37:03)
 [MSC v.1900 64 bit (AMD64)]
  Invoking CMake setup: 'cmake C:\Users\eud\AppData\Local\Temp\pip-install-f6j37
fi9\dlib\tools\python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\eud\AppData\Loca
l\Temp\pip-install-f6j37fi9\dlib\build\lib.win-amd64-3.6 -DPYTHON_EXECUTABLE=c:\
users\eud\appdata\local\programs\python\python36\python.exe -DCMAKE_LIBRARY_OUTP
UT_DIRECTORY_RELEASE=C:\Users\eud\AppData\Local\Temp\pip-install-f6j37fi9\dlib\b
uild\lib.win-amd64-3.6 -A x64'
  -- Building for: NMake Makefiles
  CMake Error in CMakeLists.txt:
    Generator

      NMake Makefiles

    does not support platform specification, but platform

      x64

    was specified.

  CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
  CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
  -- Configuring incomplete, errors occurred!
  See also "C:/Users/eud/AppData/Local/Temp/pip-install-f6j37fi9/dlib/build/temp
.win-amd64-3.6/Release/CMakeFiles/CMakeOutput.log".
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\eud\AppData\Local\Temp\pip-install-f6j37fi9\dlib\setup.py", l
ine 257, in <module>
      'Topic :: Software Development',
    File "c:\users\eud\appdata\local\programs\python\python36\lib\site-packages\
setuptools\__init__.py", line 129, in setup
      return distutils.core.setup(**attrs)
    File "c:\users\eud\appdata\local\programs\python\python36\lib\distutils\core
.py", line 148, in setup
      dist.run_commands()
    File "c:\users\eud\appdata\local\programs\python\python36\lib\distutils\dist
.py", line 955, in run_commands
      self.run_command(cmd)
    File "c:\users\eud\appdata\local\programs\python\python36\lib\distutils\dist
.py", line 974, in run_command
      cmd_obj.run()
    File "c:\users\eud\appdata\local\programs\python\python36\lib\site-packages\
wheel\bdist_wheel.py", line 188, in run
      self.run_command('build')
    File "c:\users\eud\appdata\local\programs\python\python36\lib\distutils\cmd.
py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\eud\appdata\local\programs\python\python36\lib\distutils\dist
.py", line 974, in run_command
      cmd_obj.run()
    File "c:\users\eud\appdata\local\programs\python\python36\lib\distutils\comm
and\build.py", line 135, in run
      self.run_command(cmd_name)
    File "c:\users\eud\appdata\local\programs\python\python36\lib\distutils\cmd.
py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\eud\appdata\local\programs\python\python36\lib\distutils\dist
.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Users\eud\AppData\Local\Temp\pip-install-f6j37fi9\dlib\setup.py", l
ine 133, in run
      self.build_extension(ext)
    File "C:\Users\eud\AppData\Local\Temp\pip-install-f6j37fi9\dlib\setup.py", l
ine 170, in build_extension
      subprocess.check_call(cmake_setup, cwd=build_folder)
    File "c:\users\eud\appdata\local\programs\python\python36\lib\subprocess.py"
, line 291, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\eud\\AppData\\Lo
cal\\Temp\\pip-install-f6j37fi9\\dlib\\tools\\python', '-DCMAKE_LIBRARY_OUTPUT_D
IRECTORY=C:\\Users\\eud\\AppData\\Local\\Temp\\pip-install-f6j37fi9\\dlib\\build
\\lib.win-amd64-3.6', '-DPYTHON_EXECUTABLE=c:\\users\\eud\\appdata\\local\\progr
ams\\python\\python36\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:
\\Users\\eud\\AppData\\Local\\Temp\\pip-install-f6j37fi9\\dlib\\build\\lib.win-a
md64-3.6', '-A', 'x64']' returned non-zero exit status 1.

  ----------------------------------------
  Failed building wheel for dlib
  Running setup.py clean for dlib
Failed to build dlib
Installing collected packages: dlib, scipy, scikit-learn, mtcnn, six, grpcio, ab
sl-py, termcolor, astor, html5lib, markdown, Werkzeug, bleach, protobuf, tensorb
oard, gast, tensorflow, pyyaml, keras, h5py, psutil, urllib3, chardet, idna, cer
tifi, requests, pyparsing, kiwisolver, cycler, python-dateutil, matplotlib, Pill
ow, facenet, MarkupSafe, Jinja2, click, itsdangerous, flask
  Running setup.py install for dlib ... error
    Complete output from command c:\users\eud\appdata\local\programs\python\pyth
on36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\eud\\App
Data\\Local\\Temp\\pip-install-f6j37fi9\\dlib\\setup.py';f=getattr(tokenize, 'op
en', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(
code, __file__, 'exec'))" install --record C:\Users\eud\AppData\Local\Temp\pip-r
ecord-zolrus0q\install-record.txt --single-version-externally-managed --compile:

    running install
    running build
    running build_py
    package init file 'dlib\__init__.py' not found (or not a regular file)
    running build_ext
    Building extension for Python 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 03:37:0
3) [MSC v.1900 64 bit (AMD64)]
    Invoking CMake setup: 'cmake C:\Users\eud\AppData\Local\Temp\pip-install-f6j
37fi9\dlib\tools\python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\eud\AppData\Lo
cal\Temp\pip-install-f6j37fi9\dlib\build\lib.win-amd64-3.6 -DPYTHON_EXECUTABLE=c
:\users\eud\appdata\local\programs\python\python36\python.exe -DCMAKE_LIBRARY_OU
TPUT_DIRECTORY_RELEASE=C:\Users\eud\AppData\Local\Temp\pip-install-f6j37fi9\dlib
\build\lib.win-amd64-3.6 -A x64'
    -- Building for: NMake Makefiles
    CMake Error in CMakeLists.txt:
      Generator

        NMake Makefiles

      does not support platform specification, but platform

        x64

      was specified.

    CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
    CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
    -- Configuring incomplete, errors occurred!
    See also "C:/Users/eud/AppData/Local/Temp/pip-install-f6j37fi9/dlib/build/te
mp.win-amd64-3.6/Release/CMakeFiles/CMakeOutput.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\eud\AppData\Local\Temp\pip-install-f6j37fi9\dlib\setup.py",
 line 257, in <module>
        'Topic :: Software Development',
      File "c:\users\eud\appdata\local\programs\python\python36\lib\site-package
s\setuptools\__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\eud\appdata\local\programs\python\python36\lib\distutils\co
re.py", line 148, in setup
        dist.run_commands()
      File "c:\users\eud\appdata\local\programs\python\python36\lib\distutils\di
st.py", line 955, in run_commands
        self.run_command(cmd)
      File "c:\users\eud\appdata\local\programs\python\python36\lib\distutils\di
st.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\eud\appdata\local\programs\python\python36\lib\site-package
s\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\users\eud\appdata\local\programs\python\python36\lib\distutils\co
mmand\install.py", line 545, in run
        self.run_command('build')
      File "c:\users\eud\appdata\local\programs\python\python36\lib\distutils\cm
d.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\eud\appdata\local\programs\python\python36\lib\distutils\di
st.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\eud\appdata\local\programs\python\python36\lib\distutils\co
mmand\build.py", line 135, in run
        self.run_command(cmd_name)
      File "c:\users\eud\appdata\local\programs\python\python36\lib\distutils\cm
d.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\eud\appdata\local\programs\python\python36\lib\distutils\di
st.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\eud\AppData\Local\Temp\pip-install-f6j37fi9\dlib\setup.py",
 line 133, in run
        self.build_extension(ext)
      File "C:\Users\eud\AppData\Local\Temp\pip-install-f6j37fi9\dlib\setup.py",
 line 170, in build_extension
        subprocess.check_call(cmake_setup, cwd=build_folder)
      File "c:\users\eud\appdata\local\programs\python\python36\lib\subprocess.p
y", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\eud\\AppData\\
Local\\Temp\\pip-install-f6j37fi9\\dlib\\tools\\python', '-DCMAKE_LIBRARY_OUTPUT
_DIRECTORY=C:\\Users\\eud\\AppData\\Local\\Temp\\pip-install-f6j37fi9\\dlib\\bui
ld\\lib.win-amd64-3.6', '-DPYTHON_EXECUTABLE=c:\\users\\eud\\appdata\\local\\pro
grams\\python\\python36\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=
C:\\Users\\eud\\AppData\\Local\\Temp\\pip-install-f6j37fi9\\dlib\\build\\lib.win
-amd64-3.6', '-A', 'x64']' returned non-zero exit status 1.

    ----------------------------------------
Command "c:\users\eud\appdata\local\programs\python\python36\python.exe -u -c "i
mport setuptools, tokenize;__file__='C:\\Users\\eud\\AppData\\Local\\Temp\\pip-i
nstall-f6j37fi9\\dlib\\setup.py';f=getattr(tokenize, 'open', open)(__file__);cod
e=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))
" install --record C:\Users\eud\AppData\Local\Temp\pip-record-zolrus0q\install-r
ecord.txt --single-version-externally-managed --compile" failed with error code
1 in C:\Users\eud\AppData\Local\Temp\pip-install-f6j37fi9\dlib\

C:\Users\eud\Downloads\libfaceid-master>

**Comment by edurdag** [comment]
ok solved

**Comment by richmondu** [comment]
Its a dlib installation issue. Can you share why the issue occurred in your machine and how you solved the issue?
