### ISSUE TITLE
when I want to run testing_webcam_livenessdetection.py It throws "Error, check if models and trained dataset models exists!"

### ISSUE THREAD

**Issue by hatefap** [richmondu/libfaceid#35]
first I create a virtual environment using python 3.6.8 in CentOS 7
then I activate the virtual environment and  installed the requirements using the requirements.txt file and for  installing **dlib** I installed cmake like this:
`pip install cmake`
and then clone the repo
but when I want to run this file  **testing_webcam_livenessdetection.py** like this:
 **python testing_webcam_livenessdetection.py**
this line from the testing_webcam_livenessdetection.py file throws an exception = 
f`ace_encoder = FaceEncoder(model=model_recognizer, path=INPUT_DIR_MODEL_ENCODING, path_training=INPUT_DIR_MODEL_TRAINING, training=False)`

and says `Error, check if models and trained dataset models exists!`

**Comment by FahriBilici** [comment]
Hi i am having same issue how did you fix it?

**Comment by hatefap** [comment]
Hi, you have to create some dataset with the specified format. 
If you want liveness  module only you can easily extract it.
If you need help let me know.

**Comment by FahriBilici** [comment]
> Hi, you have to create some dataset with the specified format.
> If you want liveness module only you can easily extract it.
> If you need help let me know.

Yes i added some of my pictures and run train file but it gaves me that error

**Comment by hatefap** [comment]
> > Hi, you have to create some dataset with the specified format.
> > If you want liveness module only you can easily extract it.
> > If you need help let me know.
> 
> Yes i added some of my pictures and run train file but it gaves me that error

I create my dataset like this:
dataset/person1/1.jpg
dataset/person2/2.jpg
and run the file:
`python testing_webcam_livenessdetection.py --detector 5 --encoder 3  --liveness 0 --webcam 0 --resolution 0`
and it worked!

**Comment by FahriBilici** [comment]
dataset/Fahri/1.jpeg
dataset/Fahri/2.jpeg
ans goes to 6.jpeg. it gives me
 ```
[Errno 2] No such file or directory: 'models/training/facenet_re.pickle'
Error, check if models and trained dataset models exists! 
```error. i am on linux the windows cant install dlib. i installed cmake with installer but i am guessing something wrong

**Comment by hatefap** [comment]
> dataset/Fahri/1.jpeg
> dataset/Fahri/2.jpeg
> ans goes to 6.jpeg. it gives me
> 
> ```
> [Errno 2] No such file or directory: 'models/training/facenet_re.pickle'
> Error, check if models and trained dataset models exists! 
> ```error. i am on linux the windows cant install dlib. i installed cmake with installer but i am guessing something wrong
> ```


As I remember you should first run a script that trains the model and create that file for you
Refer to readme of the project how to train the model
