### ISSUE TITLE
does the FaceID recognize me with or without glasses ?

### ISSUE THREAD

**Issue by brt-dp-rao** [richmondu/libfaceid#6]
1) does the FaceID recognize me with or without glasses ?
2) will it differentiate Natural / Real Human Face / Artificial face ?

**Comment by richmondu** [comment]
1. Yes, but fails sometimes. Yesterday 2 persons with eyeglasses tested. I think it was Thuisita and Govind. It did fail when Thuisita removed his glasses but was successful when Govind tested removing his glasses. Needs more testing and try out other models.

2. Yes, i have provided Face Liveness Detection models for anti-spoofing detection. Spoofing attacks can be photo-based, video-based and 3dmask-based. Currently there are 2 models provided: 1 for detecting eye blinking and mouth opening, and another for colorspace histogram concatenation. Yesterday, Govind tested the demo with a photo from his cellphone and the demo successfully detected it was fake.
