### ISSUE TITLE
Training File

### ISSUE THREAD

**Issue by riyajatar** [richmondu/libfaceid#7]
when i set detector to MTCNN and Encoder to FaceNet and run training.py file ...i don't get anything in training folder like embedding or label encoding...but when use default encoder detector i get those file...why?

**Comment by richmondu** [comment]
Any logs? I just tested now and it works on my side. Both MTCNN and FaceNet uses Tensorflow. Is your Tensorflow installed and working properly? Check if the version installed is same as the version specified in requirements.txt.
